name: Check Secrets

on:
  workflow_dispatch:

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Write Secret to File
        env:
          SECRET_VALUE: ${{ secrets.RENDEZVOUS_SERVER }}
        run: |
          echo "$SECRET_VALUE" > secret.txt
          echo "Secret has been written to file."

      - name: Display Secret Content
        run: cat secret.txt
