name: Check Secrets

on:
  workflow_dispatch:

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Write Secret to File
        env:
          SECRET_VALUE: ${{ secrets.RENDEZVOUS_SERVER }}
        run: |
          echo -n "$SECRET_VALUE" | sha256sum

